# System configuration
IF ( ${CMAKE_SYSTEM_NAME} STREQUAL "Emscripten" )
  	SET( CRIMILD_ENABLE_EMSCRIPTEN ON )
	ADD_DEFINITIONS( -DCRIMILD_PLATFORM_EMSCRIPTEN=1 )
ELSE ()
  	SET( CRIMILD_ENABLE_EMSCRIPTEN OFF )
ENDIF ()

IF ( APPLE )
  	 # Enable C++17 features
	 SET( CMAKE_CXX_FLAGS "-std=c++17 -stdlib=libc++ -U__STRICT_ANSI__ -fvisibility=hidden -fvisibility-inlines-hidden" )

	 SET( CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD "c++0x" )
	 SET( CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY "libc++" )

	 SET( CMAKE_MACOSX_RPATH 1 )
ELSE ( APPLE )
  	IF ( CRIMILD_ENABLE_EMSCRIPTEN )
		SET( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -static -U__STRICT_ANSI__" )
	ELSE ()
		set( CMAKE_CXX_STANDARD 20 )
		set( CMAKE_CXX_STANDARD_REQUIRED ON )
		set( CMAKE_CXX_EXTENSIONS OFF )
	ENDIF ()
ENDIF ( APPLE )
